# Generated by Django 3.2.3 on 2023-01-04 11:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_userprofile_lastperioddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastperioddate',
            field=models.DateField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
