# Generated by Django 3.2.3 on 2023-01-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodduration', to=settings.AUTH_USER_MODEL)),
                ('lasperioddate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevdate', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
