# Generated by Django 3.2.3 on 2023-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiod',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userperiod',
            name='lasperioddate',
            field=models.DateField(),
        ),
    ]
