# Generated by Django 3.0.5 on 2023-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mood',
            field=models.CharField(default='sadness', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='moodscore',
            field=models.IntegerField(default=-3),
            preserve_default=False,
        ),
    ]
