# Generated by Django 3.0.5 on 2023-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20230104_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
