# Generated by Django 3.0.5 on 2023-01-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0004_auto_20230105_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiod',
            name='uid',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
